name: pages

on:
  push:
    branches: [ "test" ]
permissions:
  contents: write

jobs:
  build:
    name: GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install mah build dependencies
        run: npm install

      - name: Build GH Pages release
        run: |
          npm run build:deploy-ghpages

      - name: Build GH Pages settings
        run: |
          touch ./dist/.nojekyll

      - name: Deploy to GH Pages branch 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
          clean: true
